#!/bin/bash

# Check difference (chkdif) script by Murray Estes
# Simple script for checking for differences between two files
# Usage: chkdif [OPTIONS] <file1> <file2>

verno="1.2.1"
auth="Murray L. Estes"
date="5 May 2021"
OPT=""
while getopts ":ysihv" opt
	do
	case ${opt} in
		y ) OPT="$OPT --side-by-side"
			;;
		s ) OPT="$OPT --suppress-common-lines"
			;;
		i ) OPT="$OPT -sq"
			;;
		h )  echo "Usage: chkdif [OPTIONS] <file1> <file2>"
		     echo "       -y - Enables --side-by-side"
		     echo "       -s - Enables --supress-common-lines"
		     echo "       -i - Only report if similar or different"
		     echo "       -v - Prints author and version information"
		     echo "       -h - Prints usage"
		     exit 0
		     	;;
		v ) echo "chkdif $verno" 
		    echo "Author: $auth"
		    echo "Last updated $date"
		    exit 0
		    	;;
		\? ) echo "Error: Invalid option passed"
		     echo "Usage: chkdif [OPTIONS] <file1> <file2>"
		     echo "       -y - Enables --side-by-side"
		     echo "       -s - Enables --supress-common-lines"
		     echo "       -i - Only report if similar or different"
		     echo "       -h - Prints usage"
		     exit 1
			;;
	esac
done

shift $((OPTIND - 1))
if [ $# -lt 2 ]
then
	echo "Error: Insufficient files for comparison"
	echo "Usage: chkdif [OPTIONS] <file1> <file2>"
	exit 1
fi

if [ ! -f $1 ]
then
	echo "Error: $1 is not a valid file"
	exit 1
fi

if [ ! -f $2 ]
then
	echo "Error: $2 is not a valid file"
	exit 1
fi

CMD=$(diff $OPT $1 $2)

if [ -z "$CMD" ]
then
	echo "Files Match."
else
	echo "$CMD"
fi
