#!/bin/bash

# Check difference (chkdif) script by Murray Estes
# Simple script for checking for differences between two files
# Usage: chkdif [OPTIONS] <file1> <file2>

OPT=""
while getopts ":ysihv" opt
	do
	case ${opt} in
		y ) OPT="$OPT --side-by-side"
			;;
		s ) OPT="$OPT --suppress-common-lines"
			;;
		i ) OPT="$OPT -sq"
			;;
		h )  echo "Usage: chkdif [OPTIONS] <file1> <file2>"
		     echo "       -y - Enables --side-by-side"
		     echo "       -s - Enables --supress-common-lines"
		     echo "       -i - Only report if similar or different"
		     echo "       -v - Prints author and version information"
		     echo "       -h - Prints usage"
		     exit 0
		     	;;
		v ) echo "chkdif v1.1.0 by Murray L. Estes"
		    echo "Last updated 9 Nov 2020"
		    exit 0
		    	;;
		\? ) echo "Error: Invalid option passed"
		     echo "Usage: chkdif [OPTIONS] <file1> <file2>"
		     echo "       -y - Enables --side-by-side"
		     echo "       -s - Enables --supress-common-lines"
		     echo "       -i - Only report if similar or different"
		     echo "       -h - Prints usage"
		     exit 1
			;;
	esac
done

shift $((OPTIND - 1))
if [ $# -lt 2 ]
then
	echo "Error: Insufficient files for comparison"
	echo "Usage: chkdif [OPTIONS] <file1> <file2>"
	exit 1
fi

CMD=$(diff $OPT $@)

if [ -z "$CMD" ]
then
	echo "Files Match."
else
	echo "$CMD"
fi
