#!/bin/bash

# Make Alias (mkalias) script by Murray Estes
# Simple script for making aliases in a bash_aliases file.
# Usage: mkalias <alias name> <commands>
# Must source bashrc file before the alias takes effect on the system.

OPT=""
while getopts ":hv" opt
do
	case ${opt} in
		h ) echo "Usage: mkalias [OPTIONS] <name> <commands>"
		    echo "       -h - Prints usage information"
		    echo "       -v - Prints author and version information"
		    exit 0
		    	;;
		v ) echo "mkalias v2.0.0 by Murray L. Estes"
		    echo "Last updated 9 Nov 2020"
		    exit 0
		    	;;
		\?) echo "Error: Invalid option passed"
		    echo "Try 'mkalias -h' for usage information"
		    exit 1
		    	;;
	esac
done

shift $((OPTIND - 1))

if [ $# -lt 2 ]
then
	echo "Usage: mkalias <alias name> <commands>"
	exit 1
fi

ALIAS_NAME="$1"
shift
ALIAS_CMD="$@"

echo alias "$ALIAS_NAME"=\'$ALIAS_CMD\' >> ~/.bash_aliases
echo "Run 'source ~/.bashrc' for the new alias $ALIAS_NAME to take effect."
exit 0
