#!/bin/bash
# remdir by Murray L. Estes
# Remove a possibly non-empty directory
# Usage: remdir <dir name>

auth="Murray L. Estes"
date="6 Jun 2021"
verno="0.0.5"
docpy=0
nodel=0
while getopts ":hvcn" opts
do
	case ${opts} in
		h )  echo "Usage: remdir [OPTION] <dir name> [<dest dir>]"
		     echo "      -h: this usage help"
		     echo "      -v: Author and version info"
		     echo "      -c: Copy contents into another directory and delete"
		     echo "      -n: Copy contents into another directory without deleting"
		     exit 0
		     ;;
		v )  echo "remdir version $verno"
		     echo "Written by $auth"
		     echo "Last update: $date"
		     exit 0
		     ;;
		c )  docpy=1
		     ;;
		n )  docpy=1;nodel=1
		     ;;
		\? ) echo "Invalid option input."
		     echo "Try 'remdir -h' for usage information."
		     exit 1
		     ;;
	esac
done
shift $((OPTIND - 1))

if [ $# -lt 1 ]
then
	echo "Error: insufficient input"
	echo "Try 'remdir -h' for usage information."
	exit 1
fi

src=$1
if [ ! -d "$src" ]
then
	echo "Error: $src is not a directory."
	echo "Try 'remdir -h' for usage information."
	exit 1
fi

if [ $docpy -eq 1 ]
then
	if [ $# -lt 2 ]
	then
		echo "Error: insufficient input"
		echo "Try 'remdir -h' for usage information."
		exit 1
	fi
	dest=$2
	if [ ! -d "$dest" ]
	then
		mkdir "$dest"
	fi
	if [ -n '$(ls -A "$src")' ]
	then
		cp -r "$src"/* "$dest"
	fi
fi

if [ $nodel -eq 0 ]
then
	rm -rf "$src" 
fi
exit 0
