#!/bin/bash

# ROS Build (rosbld) script by Murray Estes.
# Creates a catkin package for ROS projects.
# Usage: rosbld <pkg name> [<pkg options>]. 

# require at least 1 argument for package name. package options are optional
if [ $# -lt 1 ]
then
	echo "Usage: rosbld <pkg name> [<pkg options>]"
	exit 1
fi

# HOME_DIR refers to catkin workspace. Script must be placed in catkin_ws
HOME_DIR=$(pwd)
PKG_NAME=$1
shift
PKG_OPTS=$@

# Verify workspace is already created
if [ ! -f "$HOME_DIR/src/CMakeLists.txt" ]
then
	echo "$HOME_DIR is not a valid workspace. Please create a workspace prior to running rosbld."
	exit 1
fi

cd $HOME_DIR/src
if [ $PKG_OPTS ]
then
	echo "Creating Catkin Package $PKG_NAME with $PKG_OPTS..."
	catkin_create_pkg $PKG_NAME $PKG_OPTS
else
	echo "Creating Catkin Package $PKG_NAME with no options..."
	catkin_create_pkg $PKG_NAME
fi
cd $HOME_DIR
catkin_make
if [ -d "$HOME_DIR/src/$PKG_NAME/build" ]
then
	echo "build directory in $HOME_DIR/src/$PKG_NAME exists"
else
	echo "Creating build directory in $HOME_DIR/src/$PKG_NAME..."
	mkdir $HOME_DIR/src/$PKG_NAME/build
fi
cd $HOME_DIR/src/$PKG_NAME/build
cmake ..
make
if [ -d "$HOME_DIR/src/$PKG_NAME/src" ] 
then
	echo "src directory in $HOME_DIR/src/$PKG_NAME exists"
else
	echo "Creating src directory in $HOME_DIR/src/$PKG_NAME..."
	mkdir $HOME_DIR/src/$PKG_NAME/src
fi
echo "$PKG_NAME package creation complete."
exit 0
